#!/usr/bin/env python
import sys

required = open(".python-version").read().strip()
required_nums = tuple(map(int, required.split(".")))

current = sys.version.split()[0]
current_nums = sys.version_info[0:len(required_nums)]

if current_nums != required_nums:
    print(f"Python version {current} doesn't match required version {required}.", file = sys.stderr)
    sys.exit(1)
